### PR TITLE
check metadata

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
I don't think {assertr} is a good fit here, since was designed for tibbles and most elements of the metadata are single values stored in a list. {assertr} might work for checking the data structure or even the schema portion of the metadata.

**Comment by cole-brokamp** [comment]
so, circling back to our conversation today, you will merge these check functions into main after moving them into `R/codec.R`, right?

**Comment by erikarasnick** [comment]
@cole-brokamp Should I add the rest of the check functions we talked about yesterday under this PR? or merge what we have so far?

**Comment by cole-brokamp** [comment]
I think just move what you have here into that file and merge it that way.

**Comment by cole-brokamp** [comment]
> I think just move what you have here into that file and merge it that way.

scratch that!  I  misunderstood.  Yes, let's just merge this in and continue to work on the other check functions directly on `main`.

**Pull request merged**
